### ISSUE TITLE
ClientState Red5 Issue

### ISSUE THREAD

**Issue by tapfreaks** [jgh-/VideoCore#212]
<B>XCode Debugger</B>
2015-10-16 17:00:15.381 SampleBroadcaster[55322:2800260] Creating context
2015-10-16 17:00:15.554 SampleBroadcaster[55322:2800260] Context creation succeeded
Apple::AudioMixerplayPath: strex, app: liveClientState: 1
ClientState: 2
ClientState: 3
ClientState: 4
ClientState: 5
ClientState: 6
received server window size: 10000000
received peer bandwidth limit: 10000000 type: 2
received ping, sending pong.
Received invoke
pktId: 1
received invoke _result
tracked command: connect
ClientState: 7
ClientState: 11
~RTMPSession

<B>Red 5 (versions tried : 1.0.6, 1.0.4, 1.0.5):</B>

[INFO] [RTMPConnectionExecutor#ADMFZQOV0X0PR-1] org.red5.server.adapter.ApplicationAdapter - W3C x-category:session x-event:connect c-ip:192.168.8.107 c-client-id:1
[WARN] [NioProcessor-5] org.red5.server.net.rtmp.codec.RTMPProtocolDecoder - Closing connection because decoding failed: RTMPMinaConnection from 192.168.8.107 (in: 3405 out: 3354) session: ADMFZQOV0X0PR state: connected
org.red5.server.net.protocol.ProtocolException: Error during decoding
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decode(RTMPProtocolDecoder.java:190) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeBuffer(RTMPProtocolDecoder.java:114) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.red5.server.net.rtmp.codec.RTMPMinaProtocolDecoder.decode(RTMPMinaProtocolDecoder.java:77) [red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.apache.mina.filter.codec.ProtocolCodecFilter.messageReceived(ProtocolCodecFilter.java:233) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [mina-core-2.0.8.jar:na]
	at org.red5.server.net.rtmpe.RTMPEIoFilter.messageReceived(RTMPEIoFilter.java:132) [red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:48) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:943) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:109) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:542) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:535) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:714) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:668) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(AbstractPollingIoProcessor.java:657) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(AbstractPollingIoProcessor.java:67) [mina-core-2.0.8.jar:na]
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1121) [mina-core-2.0.8.jar:na]
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64) [mina-core-2.0.8.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.RuntimeException: Notify invoke / transaction id was non-zero
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeNotify(RTMPProtocolDecoder.java:793) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodeMessage(RTMPProtocolDecoder.java:530) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decodePacket(RTMPProtocolDecoder.java:371) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	at org.red5.server.net.rtmp.codec.RTMPProtocolDecoder.decode(RTMPProtocolDecoder.java:172) ~[red5-server-common-1.0.5-RELEASE.jar:1.0.5-RELEASE]
	... 22 common frames omitted
[INFO] [NioProcessor-5] org.red5.server.adapter.ApplicationAdapter - W3C x-category:session x-event:disconnect c-ip:192.168.8.107 c-client-id:1
[WARN] [NioProcessor-5] org.red5.server.net.rtmp.RTMPConnManager - Connection not found for ADMFZQOV0X0PR

**Comment by satyamub** [comment]
@tapfreaks Hi..I am using Red5 1.0.4 and I and getting the same issue. Do you mind giving me your opinion ?

**Comment by tapfreaks** [comment]
Unfortunately this project didn't work for me, might be it works with other streaming server but not with Red5 latest version, please check this one : https://github.com/pili-engineering/PLCameraStreamingKit , I tested it with Red5 latest version and it was working very well. happy coding ... :)

**Comment by bintu1234** [comment]
@tapfreaks Hi but PLCameraStreamingKit only works for pili server right? if it works with red5 can you please show some sample because i tried with PlCamera but it is not working with Red5 server.

**Comment by tapfreaks** [comment]
I have tested it over Red 5 and it was working perfectly.

**Comment by bintu1234** [comment]
@tapfreaks ok my rtmp url like this "rtmp://servername.tv/server/streamname" can you please tell me will this works?

**Comment by tapfreaks** [comment]
Yes this should work, just make sure all the necessary ports are open to use.

**Comment by tapfreaks** [comment]
Also make sure Red5 demo apps working properly on your environment.

**Comment by bintu1234** [comment]
@tapfreaks  I'm using PLCameraStreaming kit demo app in i just changed this dictionary
` streamJSON= @{@"id": @"454246",
                        @"title": @"1234",
                        @"hub": @"bintu",
                        @"publishKey": @"",
                        @"publishSecurity": @"", // or static
                        @"disabled": @(NO),
                        @"profiles": @[@"480p", @"720p"],
                  @"rtmp":@"rtmp://server.tv/server/55555",
                  };

`
but it is start the session can you please tell me where I'm missing

**Comment by tapfreaks** [comment]
This is what I used:

NSDictionary *streamJSON =
        @{//@"id": @"stream_id",
          @"title": @"test.stream",
          @"hub": @"live", //App Name
          @"publishKey": @"test.stream",
          @"publishSecurity": @"static", // or dynamic
          //@"disabled": @(NO),
          @"profiles": @[@"480p", @"720p"],    // or empty Array []
          @"hosts": @{
                  @"publish":@{
                      @"rtmp": @"192.168.8.101"
                  }
              }
          };

**Comment by bintu1234** [comment]
@tapfreaks  you said that " just make sure all the necessary ports are open to use" what are the ports we need to open can you please help me

**Comment by bintu1234** [comment]
@tapfreaks  I am getting this log what does that mean? please help me.
Problem accessing the DNS.(addr: server.tv)

**Comment by tapfreaks** [comment]
Its clearly saying your DNS is not accessible, please double check if your Red5 responding you well, secondly Red5 comes with few builtin web apps please check if you can access them on your web browser, finally I would suggest you to setup Red5 on your local machine on VM.

**Comment by bintu1234** [comment]
@tapfreaks  Thanks its working now but is this open source library or not?

**Comment by satyamub** [comment]
@bintu1234 can you tell me the red5 server address, i will try to start streaming and check?

**Comment by satyamub** [comment]
Red5 is 100 % open source!!!

**Comment by bintu1234** [comment]
I am asking about PLCameraStreaming not Red5 you can try this library it is working for me.

**Comment by satyamub** [comment]
did you not able to work with video core?

**Comment by satyamub** [comment]
@bintu1234 are you not able to use video core? if you are using red5 server can you tell me the server address so that i could start streaming to check for the compatibility?

**Comment by bintu1234** [comment]
no video core not working with the Red5 so i just shifted to another Library and i don't have red server i'm using my andorid developer local address it is like 198.0.12/yourappname/streamkey Thats why i asked you to how to install Red5 on mac.

**Comment by bintu1234** [comment]
@satyamub  If it is work with red5 please let me know then i will work with videocore only.

**Comment by satyamub** [comment]
did you try to work with cocoapod version 0.1.12 of video core?

**Comment by tapfreaks** [comment]
I spend lot of time but didn't work for me

**Comment by satyamub** [comment]
@bintu1234 @tapfreaks actually I was able to do the stream using 0.1.12, I have shared that details too with you in the past and was not able to build with cocoapod version 0.3.2 however now I know how to use this version too. So if you lag some issue with PLCameraStreaming and you want to switch to video core, you can tell me..

**Comment by bintu1234** [comment]
@satyamub  no actually i am also able to connect with videocore 0.1.12 but some bugs and every time it is not connected so thats why i looking for another library any ways PLCamera working fine but there is time difference and not playing well in player

**Comment by bintu1234** [comment]
@satyamub @tapfreaks  which Library your using for Player

**Comment by bintu1234** [comment]
@satyamub  is it working with the red5 using Videocore 0.3.2

**Comment by bintu1234** [comment]
@tapfreaks is  PLCamerastrteaming working fine for you. I am able to broadcast but unable to play the live stream perfectly it is not showing video as i am recording delay with 20 sec and struck playing for while  plaese help me

**Comment by bintu1234** [comment]
@sathyamob please help me is it working with the red5 or not.

**Comment by satyamub** [comment]
@bintu1234 I am working on red5 setup now... when the server setup is finish, I will start the stream and let you know!!

**Comment by satyamub** [comment]
@tapfreaks if you people have any red5 live server then let me know.. I try to stream there and let you know the results!!!!

**Comment by bintu1234** [comment]
@satyamub  can you please give me you mail then i will send my red5 server Thankyou

**Comment by bintu1234** [comment]
@satyamub  i will send my red5 server name please give me your mailid

**Comment by satyamub** [comment]
satya.saphire@gmail.com

**Comment by bintu1234** [comment]
@satyamub Can you please check your mail i send my Red5 server name
